name: Lint Shaka Packager

description: |
  A reusable action to lint Shaka Packager source.
  When checking out source, you must use 'fetch-depth: 2' in actions/checkout,
  or else the linter won't have another revision to compare to.

runs:
  using: composite
  steps:
    - name: Lint
      shell: bash
      run: |
        cd src/
        echo "::group::Installing git-clang-format"
        wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format
        sudo install -m 755 git-clang-format /usr/local/bin/git-clang-format
        rm git-clang-format
        echo "::endgroup::"
        echo "::group::Installing pylint"
        python3 -m pip install --upgrade pylint
        echo "::endgroup::"
        echo "::group::Check clang-format for C++ sources"
        # NOTE: --binary forces use of global clang-format (which works) instead
        # of depot_tools clang-format (which doesn't).
        # NOTE: Must use base.sha instead of base.ref, since we don't have
        # access to the branch name that base.ref would give us.
        # NOTE: Must also use fetch-depth: 2 in actions/checkout to have access
        # to the base ref for comparison.
        packager/tools/git/check_formatting.py \
            --binary /usr/bin/clang-format \
            ${{ github.event.pull_request.base.sha || 'HEAD^' }}
        echo "::endgroup::"
        echo "::group::Check pylint for Python sources"
        packager/tools/git/check_pylint.py
        echo "::endgroup::"
